\version "2.26.0"
% Generated by kapell engrave against the project's shared music.
\include "music-global.ly"
\include "music-voices.ly"
@DEFINITIONS@

\header {
  title = "@TITLE@"
  subtitle = "@SUBTITLE@"
  tagline = ##f
}
\paper { #(set-paper-size "a4") ragged-last-bottom = ##t }
\markup \small \wordwrap { "@NOTICE@" }

#(set-global-staff-size 15)
\score {
  <<
    \new PianoStaff \with { instrumentName = "Piano" shortInstrumentName = "Pno." } <<
      \new Staff << \global \marks
        \new Voice { \voiceOne \pianoSoprano }
        \new Voice { \voiceTwo \pianoAlto }
      >>
      \new Dynamics \dynamicsLine
      \new Staff << \global \clef bass
        \new Voice { \voiceOne \pianoTenor }
        \new Voice { \voiceTwo \pianoBass }
      >>
    >>
    \new StaffGroup <<
      \new Staff \with { instrumentName = "Violin I" shortInstrumentName = "Vln. I" } <<
        \global \violinOne \dynamicsLine >>
      \new Staff \with { instrumentName = "Violin II" shortInstrumentName = "Vln. II" } <<
        \global \violinTwo \dynamicsLine >>
      \new Staff \with { instrumentName = "Viola" shortInstrumentName = "Vla." } <<
        \global \clef alto \viola \dynamicsLine >>
      \new Staff \with { instrumentName = "Violoncello" shortInstrumentName = "Vc." } <<
        \global \clef bass \cello \dynamicsLine >>
    >>
  >>

  \layout {
    \context { \Score
      barNumberVisibility = #all-bar-numbers-visible
      \override BarNumber.break-visibility = #end-of-line-invisible
      \override BarNumber.font-size = #-2 }
  }
}
