\version "2.26.0"
% Generated by kapell engrave against the project's shared music.
\include "music-global.ly"
\include "music-voices.ly"
@DEFINITIONS@

\header {
  title = "@TITLE@"
  subtitle = "@SUBTITLE@"
  tagline = ##f
}
\paper { #(set-paper-size "a4") ragged-last-bottom = ##t }
\markup \small \wordwrap { "@NOTICE@" }

#(set-global-staff-size 15)
\score {
  <<
    \new StaffGroup \with { instrumentName = "Woodwinds" shortInstrumentName = "Ww." } <<
      \new Staff << \global \marks
        \new Voice { \voiceOne \windsSoprano }
        \new Voice { \voiceTwo \windsAlto }
      >>
      \new Dynamics \dynamicsLine
      \new Staff << \global \clef bass
        \new Voice { \voiceOne \windsTenor }
        \new Voice { \voiceTwo \windsBass }
      >>
    >>
    \new StaffGroup \with { instrumentName = "Brass" shortInstrumentName = "Br." } <<
      \new Staff << \global 
        \new Voice { \voiceOne \brassSoprano }
        \new Voice { \voiceTwo \brassAlto }
      >>
      \new Dynamics \dynamicsLine
      \new Staff << \global \clef bass
        \new Voice { \voiceOne \brassTenor }
        \new Voice { \voiceTwo \brassBass }
      >>
    >>
    \new StaffGroup \with { instrumentName = "Strings" shortInstrumentName = "Str." } <<
      \new Staff << \global 
        \new Voice { \voiceOne \stringsSoprano }
        \new Voice { \voiceTwo \stringsAlto }
      >>
      \new Dynamics \dynamicsLine
      \new Staff << \global \clef bass
        \new Voice { \voiceOne \stringsTenor }
        \new Voice { \voiceTwo \stringsBass }
      >>
    >>
  >>

  \layout {
    \context { \Score
      barNumberVisibility = #all-bar-numbers-visible
      \override BarNumber.break-visibility = #end-of-line-invisible
      \override BarNumber.font-size = #-2 }
  }
}
