\version "2.26.0"
% Generated by kapell engrave against the project's shared music.
\include "music-global.ly"
\include "music-voices.ly"
@DEFINITIONS@

\header {
  title = "@TITLE@"
  subtitle = "@SUBTITLE@"
  tagline = ##f
}
\paper { #(set-paper-size "a4") ragged-last-bottom = ##t }
\markup \small \wordwrap { "@NOTICE@" }

\score {
  \new StaffGroup <<
    \new PianoStaff \with { instrumentName = "Manuals" shortInstrumentName = "Man." } <<
      \new Staff = "manualOne" \with { instrumentName = "I" shortInstrumentName = "I" } <<
        \global \marks
        \new Voice { \registrationCues }
        \new Voice { \voiceOne \soprano }
        \new Voice { \voiceTwo \alto }
      >>
      \new Staff = "manualTwo" \with { instrumentName = "II" shortInstrumentName = "II" } <<
        \global \clef bass \tenor
      >>
    >>
    \new Staff = "pedal" \with { instrumentName = "Pedal" shortInstrumentName = "Ped." } <<
      \global \clef bass \bass
    >>
  >>

  \layout {
    \context { \Score
      barNumberVisibility = #all-bar-numbers-visible
      \override BarNumber.break-visibility = #end-of-line-invisible
      \override BarNumber.font-size = #-2 }
  }
}
